---
title: "`r params$exposure` posthoc analysis"
date: '`r paste("Updated on", Sys.Date())`'
output: 
  html_document:
    css: posthoc/posthoc_report.css
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
    toc_depth: 3
    theme: "paper"
params:
  exposure: "bmi5"
  covariates: !r c("age_ref_imp", "sex", "pc1", "pc2", "pc3", "study_gxe")
  covariates_smk: !r c("age_ref_imp", "sex", "pc1", "pc2", "pc3", "study_gxe", "smk_ever")
  hrc_version: "v2.3"
  # path: "/media/work/gwis_test"
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = F, message = F, warning = F, error = F)

# load packages and define wrapper functions
library(tidyverse)
library(data.table)
library(forcats)
library(ggplot2)
library(qqman)
library(rlang)
library(figifs)
library(DT)
library(grid)
library(stargazer)
library(kableExtra)
library(formattable)
library(glue)
library(qs)

path <- glue("/media/work/gwis_test/{params$exposure}/")

# assign variables
child_env <- new.env()           
assign("exposure", params$exposure, child_env)
assign("hrc_version", params$hrc_version, child_env)
assign("covariates", sort(params$covariates), child_env)
assign("covariates_smk", sort(params$covariates_smk), child_env)
assign("method", "chiSqGxE", child_env)
```


Original top hit (**chr15_33122966_C_T**) is a multi-allelic site and is causing issues when I try to calculate LD. So for functional annotation + regional plots I’ll report results for both **chr15_33122966_C_T** and the second most sig GxE hit, **chr15_33120215_T_C** (r^2 = 0.987729)

# chr15_33122966_C_T
```{r, include = F}
assign("snp", "chr15_33122966_C_T", child_env)
```
```{r, results = 'asis'}
res <- knitr::knit_child('posthoc/posthoc_child_bmi.Rmd', quiet = TRUE, envir = child_env)
cat(res, sep = '\n')
```



# chr15_33120215_T_C
```{r, include = F}
assign("snp", "chr15_33120215_T_C", child_env)
```
```{r, results = 'asis'}
res <- knitr::knit_child('posthoc/posthoc_child_bmi.Rmd', quiet = TRUE, envir = child_env)
cat(res, sep = '\n')
```





