---
title: "`r params$exposure` posthoc analysis"
date: '`r paste("Updated on", Sys.Date())`'
output: 
  html_document:
    css: posthoc/posthoc_report.css
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 3
    theme: "paper"
params:
  exposure: "redmeatqcm_v2"
  covariates: !r c("age_ref_imp", "sex", "energytot_imp", "pc1", "pc2", "pc3", "study_gxe")
  hrc_version: "v3.0"
  path: "/media/work/gwis_test"
---

  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F, error = F)
# load packages and define wrapper functions
library(tidyverse)
library(data.table)
library(forcats)
library(ggplot2)
library(qqman)
library(rlang)
library(figifs)
library(DT)
library(grid)
library(stargazer)
library(kableExtra)
library(formattable)
library(glue)


# parameters
exposure = params$exposure
covariates = c("age_ref_imp",
               "sex",
               "energytot_imp",
               "pc1",
               "pc2",
               "pc3",
               "study_gxe")
hrc_version = params$hrc_version
path = glue("/media/work/gwis_test/{params$exposure}")
```


---

<!-- read script containing useful chunks -->
```{r child = 'posthoc/chunks.Rmd'}
```

# Suggestive GxE (P < 5e-6)

```{r, results = 'asis'}
statistic = 'chiSqGxE'

# list of SNPs
snps <- c("17:71354811:G:A", "9:120653523:T:G", "4:31160820:G:A", "9:120290042:A:G", "8:122247679:C:G", "1:21495668:G:T", "3:29246192:C:T", "1:21209766:T:A", "15:100002029:C:T", "8:112374447:C:T", "18:21029284:C:T", "20:51479759:G:T", "2:42324419:T:A", "10:29013189:C:T", "13:62734417:A:G", "1:41466550:T:A", "3:27633795:G:A", "2:73204203:G:A", "1:239473113:T:C")
snps <- paste0('chr', gsub(":", "_", snps))


# see chunks.Rmd for names
run_functions <- function(snp) {
  <<title>>
  <<allele_freq_plots>>
  <<stratified_or_cont>>
  <<interaction_plots>>
  <<locuszoom_plots>>
  # <<functional_plots>>
}

# run
walk(snps, ~ run_functions(.x))

```


# 2DF findings
```{r, results = 'asis'}
statistic = 'chiSqGxE'

# list of SNPs
snps <- c("8:120042899:G:T", "8:122247679:C:G", "10:86469912:G:A")
snps <- paste0('chr', gsub(":", "_", snps))

# see chunks.Rmd for names
run_functions <- function(snp) {
  <<title>>
  <<allele_freq_plots>>
  <<gxe_stratified_sex>>
  <<gxe_stratified_study>>
  <<gxe_stratified_tumorsite>>
  <<stratified_or_cont>>
  <<interaction_plots>>
  <<locuszoom_plots>>
  <<functional_plots>>
}

# run
walk(snps, ~ run_functions(.x))
```




# 3DF findings
(same locus as 2DF) -- see above


# Two-step findings
```{r, results = 'asis'}
statistic = 'chiSqGxE'

# list of SNPs
snps <- c("18:46453754:C:T")
snps <- paste0('chr', gsub(":", "_", snps))

# see chunks.Rmd for names
run_functions <- function(snp) {
  <<title>>
  <<allele_freq_plots>>
  <<gxe_stratified_sex>>
  <<gxe_stratified_study>>
  <<gxe_stratified_tumorsite>>
  <<stratified_or_cont>>
  <<interaction_plots>>
  <<locuszoom_plots>>
  <<functional_plots>>
}

# run
walk(snps, ~ run_functions(.x))
```





# E|G finding (combined case-control sample)
(SNP associated with meat intake)

```{r, results = 'asis'}
# Note: Summarizing the E|G association - stratified ables below report E|G model parameters, not GxE

statistic = 'chiSqGE'

# list of SNPs
snps <- c("19:49232226:G:A")
snps <- paste0('chr', gsub(":", "_", snps))

# see chunks.Rmd for names
run_functions <- function(snp) {
  <<title>>
  <<allele_freq_plots>>
  <<locuszoom_plots>>
  <<functional_plots>>
}

# run
walk(snps, ~ run_functions(.x))

```

