```{r helper_pooled, include = F}
# helper function to create filename suffix 
# for pooled analysis i only created sex/study_design/cancersite stratified tables
create_suffix <- function(strata) {
  paste0(paste0(sort(params$covariates), collapse = '_'), "_stratified_", strata, ".html")
}

# don't stratify by sex if exposure is HRT
if(params$exposure %in% c("hrt_ref_pm2", "eo_ref_pm_gxe", "ep_ref_pm_gxe", "pure_eo_allNo", "pure_ep_allNo")) {
  stratify_by_sex = F
} else {
  stratify_by_sex = T
}

# output dir
output_dir_meta <- glue("/media/work/gwis/posthoc/{params$exposure}/")

```

#### Sex
```{r, results = 'asis', echo = F, quote = F, message = F, eval = stratify_by_sex}
pooled_suffix_sex <- create_suffix('sex')

rawHTML <- paste(readLines(paste0(output_dir_meta <- glue("/media/work/gwis/posthoc/{params$exposure}/")
, "main_effects_pooled_analysis_", params$exposure, "_", pooled_suffix_sex)))
cat(paste(rawHTML, collapse = "\n"), "\n")
```

#### Tumor site
```{r, results = 'asis', echo = F, quote = F, message = F}
pooled_suffix_tumor_site <- create_suffix('cancer_site_sum2')

rawHTML <- paste(readLines(paste0(output_dir_meta <- glue("/media/work/gwis/posthoc/{params$exposure}/")
, "main_effects_pooled_analysis_", params$exposure, "_", pooled_suffix_tumor_site)))
cat(paste(rawHTML, collapse = "\n"), "\n")
```

#### Study design
```{r, results = 'asis', echo = F, quote = F, message = F}
pooled_suffix_study_design <- create_suffix('study_design')

rawHTML <- paste(readLines(paste0(output_dir_meta <- glue("/media/work/gwis/posthoc/{params$exposure}/")
, "main_effects_pooled_analysis_", params$exposure, "_", pooled_suffix_study_design)))
cat(paste(rawHTML, collapse = "\n"), "\n")
```